# Generated by Django 4.0.2 on 2022-02-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_mon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fan',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
    ]
