# Generated by Django 4.0.4 on 2022-04-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_mon', '0002_alter_device_content_alter_fan_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='thermal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
