# Generated by Django 4.0.4 on 2022-04-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_mon', '0003_fan_thermal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fan',
            name='thermal',
        ),
    ]
